---
title: "SaS Scoring Re-Certification Reports"
subtitle: "A Component of the NIH BabyTB Training Re-Certification Shiny App"
author: "Elizabeth Dworak"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  github_document:
    toc: true
  html_document:
    toc: true
    toc_float: true
    highlight: "tango"
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
```

# Overview

Welcome to the NBT Sit and Stand (SaS) Scoring Re-Certification Reports folder (`scoring_input`). This folder includes code used for cleaning, (re)scoring, ana analyzing the data collected from the SaS re-certification Shiny application. 


# Folder organization

As of `r format(Sys.time(), '%B %Y')`, this folder contains a limited number of files used to clean, (re)score, and analyze data from the Shiny application. Likewise, code in this folder creates individualized reports for those undergoing scoring certification. Below is a brief description of the organization of the files and folders:

-   `sas_certification_results.Rmd` - This file contains the primary code to run, (re)score, and analyze data from the NBT training SaS re-certification Shiny application and is intended to give those overseeing training an overview of how trainees are performing on a new set of SaS videos. When cleaning the data, this code will tell you 1) who was inconsistent when entering their name and make corrections to these errors; 2) who took an assessment multiple times and drop duplicates; and 3) who has completed all the required assessments verses who has missing scoring certification data. As there were errors during the initial deployment of the training certification Shiny application, this code will also correct input errors and rescore the data to get an accurate representation of how trainees are performing. After cleaning and scoring the data, it then generates subsections to tell those certifying trainees how their overall (i.e., assessment) and item level performance was. 

-   `sas_individual_results.Rmd` - This file contains a the code used to generate individual PDF reports that can be returned to the trainees undergoing SaS scoring re-certification. These reports include how the trainee's overall (i.e., assessment) and item level performance was. This includes listing out the measure, question, video, response, answer key, and score. 

-   `data` - This folder contains the unprocessed and processed data produced by the Shiny application. Data from this folder are required in order to run the `sas_certification_results.Rmd` and `sas_individual_results.Rmd`. The file has been uploaded to show the structure to those interested in creating their own Shiny application. For those on the NBT team interested in obtaining the data, please contact someone on the NBT data team.  

-   `individual_reports` - This folder contains the individual reports produced by `sas_individual_results.Rmd` organized by collection site. The file has been uploaded to show the structure to those interested in creating their own Shiny application.
