---
title: "BabyTB GitHub Repository"
author: "Aaron Kaat, Elizabeth Dworak, and Hugh Adams"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  github_document:
    toc: true
  html_document:
    toc: true
    toc_float: true
    highlight: "tango"
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
```

# Overview

Welcome to the BabyTB GitHub Repository. This repository includes a variety of projects and code used for the development and training involved with the NIH Infant and Toddler Toolbox (BabyTB).

# What is BabyTB?

While there are several well-known assessment batteries for use by children under the age of 4, there is no standardized direct developmental assessments of infants and young children that is inexpensive, easy to administer within a relatively brief time frame, and able to capture multiple domains of neurodevelopment across this age range. The NIH Infant and Toddler Toolbox (aka the “NIH Baby Toolbox” or BabyTB) aims to develop, validate and norm an efficient, comprehensive neurodevelopmental battery of measures for tablet based administration. It will be specific for use by researchers and clinicians in the neuropsychological, cognitive and social assessment of infants and toddlers ages 1 – 42 months.

# Repo organization

As of April 2023, this repo is organized into two folders. Each folder will have a README that explains the purpose of the folder as well as the necessary steps to run and/or obtain the files in that folder. Below is a brief description of the organization of the folders:

-   `training_certification` - This folder contains the code to run the Shiny App designed for scoring certification for those undergoing training on the BabyTB.

-   `dry_run` - This folder contains scripts related to obtaining, cleaning, and analyzing dats collected during the March 2023 Dry Run data collection. It also include scripts that show the results of these analyses. 


